"""empty message

Revision ID: 1eb149a387a7
Revises: 880c5dffa8a4
Create Date: 2023-03-08 14:39:00.307165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb149a387a7'
down_revision = '880c5dffa8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash', sa.Text(), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('hash')

    # ### end Alembic commands ###
