"""empty message

Revision ID: 880c5dffa8a4
Revises: 8bae2fc2ba59
Create Date: 2023-03-08 14:05:38.268596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880c5dffa8a4'
down_revision = '8bae2fc2ba59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
